import mongoose from 'mongoose'

const InterviewSchema = new mongoose.Schema(
  {
    topic: {
      type: String,
      enum: [
        // 'Academico_Universitario',
        // 'Problemas_y_o_conflictos_familiares',
        // 'Auxilio_matricula',
        // 'Auxilio_manutencion',
        // 'Auxilio_plan_de_trabajo',
        // 'Bautismo_por_primera_vez_en_la_IASD',
        // 'Bautismo_por_segunda_vez_en_la_IASD',
        // 'Toma_de_profesion_de_posesion_en_la_IASD',
        // 'Toma_de_estudios_biblicos_para_bautismo_en_la_IASD',
        // 'Desercion_de_la_IASD',
        // 'Salud',
        // 'Deportes',
        // 'Clubes_adventistas',
        // 'Especiales_de_cantos_musicas_conciertos',
        // 'Ministerios_Adventistas',
        // 'Violacion',
        'Académico - Universitario',
        'Problemas y/o conflictos familiares',
        'Apoyo económico para matricula',
        'Apoyo económico para manutención',
        'Apoyo económico para plan de trabajo',
        'Bautismo por primera vez en la IASD',
        'Bautismo por segunda vez en la IASD',
        'Toma de profesión de posesión en la IASD',
        'Toma de estudios bíblicos para bautismo en la IASD',
        'Deserción de la IASD',
        'Salud',
        'Gratitud',
        'Deportes',
        'Clubes adventistas',
        'Especiales de cantos, músicas, conciertos',
        'Ministerios Adventistas',
        'Violacion',
      ],
      default: 'Académico - Universitario',
    },
    topicDescription: {
      type: String,
      required: true,
      trim: true,
    },
    actionsDescription: {
      type: String,
      required: true,
    },
    referralDepartment: {
      type: String,
      enum: [
        'No necesita remisión',
        'Centro de Psicología',
        'Centro de Pediatría',
        'Centro de atención al estudiante',
        'Recpectivo decano de la facultad de la carrera',
        'Coordinador del programa',
        'Pastor actual de la iglesia',
        'Rector de la universidad',
        'Precentor de internos',
        'Precentor de externos',
        'Vicerrectoría Académica',
        'Vicerrectoría Estudiantil',
        'Admisiones',
        'Finanzas',
      ],
      default: 'No necesita remisión',
    },
    status: {
      type: String,
      enum: ['Pendiente', 'Cancelada', 'Completada'],
      default: 'Pendiente',
    },
    beneficiary: {
      type: String,
      required: true,
      trim: true,
    },
    userCreate: {
      type: String,
      required: true,
      trim: true,
    },
    userUpdate: {
      type: String,
      required: true,
      trim: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
)

export default mongoose.model('Interview', InterviewSchema)
